// Provider Card Configuration
// Add new providers here - no need to create new component files!

// Provider config — gambar kartu dari provider-mock-animated-images.json (public/animated-brand)
import providerMockAnimatedImages from '../data/provider-mock-animated-images.json'
import { providerAssetUrl } from '../utils/publicAssetUrl'

function pImg(providerId) {
  return providerMockAnimatedImages[String(providerId)] ?? null
}

function mapProviderImages(list) {
  return list.map((p) => {
    const { characterImg, logoImg, overlayImg, ...rest } = p
    const url = pImg(rest.provider_id)
    const resolved = url ? providerAssetUrl(url) : null
    return {
      ...rest,
      characterImg: resolved,
      logoImg: resolved,
      overlayImg: null,
    }
  })
}

/**
 * Provider Configuration
 * 
 * Each provider object can have these properties:
 * - id: string (required) - unique identifier
 * - name: string (required) - display name
 * - characterImg: string (required) - main character image
 * - characterImgAlt: string - alt text for character
 * - logoImg: string (required) - provider logo image
 * - logoAlt: string - alt text for logo
 * - logoWidth: string - logo width CSS value (default: '150px')
 * - logoTop: string - logo top position CSS value (default: '20px')
 * - logoLeft: string - logo left position CSS value (default: '46%')
 * - characterWidth: string - character container width (Tailwind class)
 * - characterPosition: string - character position classes
 * - characterCentered: boolean - if true, centers character vertically
 * - glowColor: 'white' | 'orange' | 'yellow' | 'red' | 'cyan' | 'purple'
 * - glowColorHover: same as above - glow color on hover
 * - badge: { type: 'hot' | 'new' | 'top' | null }
 * - overlayImg: string - optional overlay image (e.g., lightning)
 * - animationPrefix: string - CSS animation class prefix
 */

const providersRaw = [
  {
    id: 'pragmatic-play',
    provider_id: 1001,
    name: 'Pragmatic Play',
    characterImgAlt: 'Zeus',
    logoAlt: 'Pragmatic Play',
    logoWidth: '800px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-10px] bottom-[-10px]',
    characterCentered: false,
    glowColor: 'white',
    glowColorHover: 'cyan',
    badge: { type: 'hot' },
    animationPrefix: 'zeus',
  },
  {
    id: 'pg-soft',
    provider_id: 1002,
    name: 'PG Soft',
    characterImgAlt: 'Mariachi Skeleton',
    logoAlt: 'PG Soft',
    logoWidth: '160px',
    logoTop: '30px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-10px] bottom-[-12px]',
    characterCentered: false,
    glowColor: 'orange',
    glowColorHover: 'orange',
    badge: { type: 'new' },
    animationPrefix: 'mariachi',
  },
  {
    id: 'nolimit-city',
    provider_id: 1003,
    name: 'Nolimit City',
    characterImgAlt: 'Cleopatra',
    logoAlt: 'Nolimit City',
    logoWidth: '600px',
    logoTop: '30px',
    logoLeft: '46%',
    characterWidth: 'w-[52%]',
    characterPosition: 'left-[-5px] bottom-[-8px]',
    characterCentered: false,
    glowColor: 'yellow',
    glowColorHover: 'yellow',
    badge: null,
    animationPrefix: 'cleopatra',
  },
  {
    id: 'lucky-monaco',
    provider_id: 1004,
    name: 'Lucky Monaco',
    characterImgAlt: 'Chinese Empress',
    logoAlt: 'Lucky Monaco',
    logoWidth: '200px',
    logoTop: '24px',
    logoLeft: '44%',
    characterWidth: 'w-[54%]',
    characterPosition: 'left-[-8px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'red',
    badge: null,
    animationPrefix: 'empress',
  },
  {
    id: 'joker',
    provider_id: 1005,
    name: 'Joker Gaming',
    characterImgAlt: 'Spartan Warrior',
    logoAlt: 'Joker',
    logoWidth: '250px',
    logoTop: '-15px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-8px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'yellow',
    badge: null,
    animationPrefix: 'spartan',
  },
  {
    id: 'cq9',
    provider_id: 1006,
    name: 'JDB',
    characterImgAlt: 'Panda Warrior',
    logoAlt: 'JDB',
    logoWidth: '170px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    badge: null,
    animationPrefix: 'panda',
  },
  {
    id: 'habanero',
    provider_id: 1007,
    name: 'Habanero',
    characterImgAlt: 'Gangster',
    logoAlt: 'Habanero',
    logoWidth: '180px',
    logoTop: '30px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'red',
    badge: null,
    animationPrefix: 'gangster',
  },
  {
    id: 'yggdrasil',
    provider_id: 1008,
    name: 'Yggdrasil',
    characterImgAlt: 'Soldier',
    logoAlt: 'Yggdrasil',
    logoWidth: '400px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px], bottom-[-60px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'white',
    badge: null,
    animationPrefix: 'soldier',
  },
  {
    id: 'worldmatch',
    provider_id: 1009,
    name: 'WorldMatch',
    characterImgAlt: 'Cowgirl',
    logoAlt: 'WorldMatch',
    logoWidth: '170px',
    logoTop: '15px',
    logoLeft: '46%',
    characterWidth: 'w-[48%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'white',
    badge: null,
    animationPrefix: 'cowgirl',
  },
  {
    id: 'sboslot',
    provider_id: 1010,
    name: 'SBOSLOT',
    characterImgAlt: 'Viking Warrior',
    logoAlt: 'SBOSLOT',
    logoWidth: '180px',
    logoTop: '50px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    badge: null,
    animationPrefix: 'viking',
  },
  {
    id: 'funkygames',
    provider_id: 1011,
    name: 'Funky Games',
    characterImgAlt: 'King',
    logoAlt: 'Funky Games',
    logoWidth: '200px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'purple',
    glowColorHover: 'white',
    badge: null,
    animationPrefix: 'king',
  },
  {
    id: 'microgaming',
    provider_id: 1012,
    name: 'Microgaming',
    characterImgAlt: 'Fire Skeleton Guitarist',
    logoAlt: 'Microgaming',
    logoWidth: '300px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-60px]',
    characterCentered: false,
    glowColor: 'orange',
    glowColorHover: 'red',
    badge: null,
    animationPrefix: 'firerock',
  },
  {
    id: 'netent',
    provider_id: 1013,
    name: 'NetEnt',
    characterImgAlt: 'Aladdin',
    logoAlt: 'NetEnt',
    logoWidth: '180px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'yellow',
    badge: null,
    animationPrefix: 'aladdin',
  },
  {
    id: 'afb777',
    provider_id: 1014,
    name: 'AFB777 Gaming',
    characterImgAlt: 'Boxer',
    logoAlt: 'AFB777 Gaming',
    logoWidth: '180px',
    logoTop: '30px',
    logoLeft: '45%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'orange',
    badge: null,
    animationPrefix: 'boxer',
  },
  {
    id: 'jili',
    provider_id: 1015,
    name: 'JILI',
    characterImgAlt: 'Sultan',
    logoAlt: 'JILI',
    logoWidth: '150px',
    logoTop: '5px',
    logoLeft: '46%',
    characterWidth: 'w-[45%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    badge: null,
    animationPrefix: 'sultan',
  },
  {
    id: 'rich88',
    provider_id: 1016,
    name: 'RICH88',
    characterImgAlt: 'Genie',
    logoAlt: 'RICH88',
    logoWidth: '160px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'yellow',
    badge: null,
    animationPrefix: 'genie',
  },
  {
    id: 'advantplay',
    provider_id: 1017,
    name: 'AdvantPlay',
    characterImgAlt: 'Poseidon',
    logoAlt: 'AdvantPlay',
    logoWidth: '160px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    badge: null,
    animationPrefix: 'poseidon',
  },
  {
    id: 'kingmaker',
    provider_id: 1018,
    name: 'Kingmaker',
    characterImgAlt: 'Pirate',
    logoAlt: 'Kingmaker',
    logoWidth: '180px',
    logoTop: '15px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    badge: null,
    animationPrefix: 'pirate',
  },
  {
    id: 'ygr',
    provider_id: 1019,
    name: 'YGR Gaming',
    characterImgAlt: 'Warrior',
    logoAlt: 'YGR Gaming',
    logoWidth: '160px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'yellow',
    badge: null,
    animationPrefix: 'warrior',
  },
  {
    id: 'playstar',
    provider_id: 1020,
    name: 'PlayStar',
    characterImgAlt: 'Pharaoh',
    logoAlt: 'PlayStar',
    logoWidth: '180px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'purple',
    badge: null,
    animationPrefix: 'pharaoh',
  },
  {
    id: 'fastspin',
    provider_id: 1021,
    name: 'FastSpin',
    characterImgAlt: 'Mad Scientist',
    logoAlt: 'FastSpin',
    logoWidth: '180px',
    logoTop: '30px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'green',
    glowColorHover: 'purple',
    badge: null,
    animationPrefix: 'scientist',
  },
  {
    id: 'dragoonsoft',
    provider_id: 1022,
    name: 'Dragoon Soft',
    characterImgAlt: 'Dragon',
    logoAlt: 'Dragoon Soft',
    logoWidth: '180px',
    logoTop: '40px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-10px]',
    characterCentered: true,
    glowColor: 'green',
    glowColorHover: 'orange',
    badge: null,
    animationPrefix: 'dragon',
  },
  {
    id: 'nagagames',
    provider_id: 1023,
    name: 'Naga Games',
    characterImgAlt: 'Monopoly Man',
    logoAlt: 'Naga Games',
    logoWidth: '180px',
    logoTop: '-15px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'green',
    badge: null,
    animationPrefix: 'monopoly',
  },
]

const slotPartnerProvidersRaw = Array.from({ length: 31 }, (_, i) => {
  const n = i + 1
  return {
    id: `slot-partner-${n}`,
    provider_id: 1023 + n,
    name: `Slot Partner ${n}`,
    characterImgAlt: 'Slot character',
    logoAlt: 'Slot',
    logoWidth: '180px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-10px] bottom-[-12px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'purple',
    badge: null,
    animationPrefix: 'slotpartner',
  }
})

export const providers = mapProviderImages([...providersRaw, ...slotPartnerProvidersRaw])

// ========== SPORTS PROVIDERS ==========
const sportsProvidersRaw = [
  {
    id: 'sbobet',
    provider_id: 4001,
    name: 'SBOBET',
    characterImgAlt: 'Lamine Yamal',
    logoAlt: 'SBOBET',
    logoWidth: '200px',
    logoTop: '45px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'footballer',
  },
  {
    id: 'saba-sports',
    provider_id: 4002,
    name: 'SABA Sports',
    characterImgAlt: 'Mbappe',
    logoAlt: 'SABA Sports',
    logoWidth: '200px',
    logoTop: '30px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-0px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'white',
    animationPrefix: 'footballer',
  },
  {
    id: 'afb777-sports',
    provider_id: 4003,
    name: 'AFB777 Gaming',
    characterImgAlt: 'Haaland',
    logoAlt: 'AFB777 Gaming',
    logoWidth: '200px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-15px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'cyan',
    animationPrefix: 'footballer',
  },
  {
    id: 'bti',
    provider_id: 4004,
    name: 'BTi',
    characterImgAlt: 'Messi',
    logoAlt: 'BTi',
    logoWidth: '180px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px] bottom-[-80px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'yellow',
    animationPrefix: 'footballer',
  },
  {
    id: 'betpanda',
    provider_id: 4005,
    name: 'Betpanda',
    characterImgAlt: 'Ronaldo',
    logoAlt: 'Betpanda',
    logoWidth: '200px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-10px] bottom-[-75px]',
    characterCentered: true,
    glowColor: 'green',
    glowColorHover: 'yellow',
    animationPrefix: 'footballer',
  },
  {
    id: 'cmd368',
    provider_id: 4006,
    name: 'CMD368',
    characterImgAlt: 'Sports',
    logoAlt: 'CMD368',
    logoWidth: '200px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'footballer',
  },
  {
    id: 'lucky-sports-plus',
    provider_id: 4007,
    name: 'Lucky Sports',
    characterImgAlt: 'Sports',
    logoAlt: 'Lucky Sports',
    logoWidth: '200px',
    logoTop: '30px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-0px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'white',
    animationPrefix: 'footballer',
  },
  {
    id: 'united-gaming',
    provider_id: 4008,
    name: 'United Gaming',
    characterImgAlt: 'Sports',
    logoAlt: 'United Gaming',
    logoWidth: '200px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-15px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'cyan',
    animationPrefix: 'footballer',
  },
]

export const sportsProviders = mapProviderImages(sportsProvidersRaw)

// ========== CASINO PROVIDERS ==========
// Paired: model1 + kasino1, model2 + kasino2, etc.
const casinoProvidersRaw = [
  {
    id: '568win',
    provider_id: 3001,
    name: '568Win',
    characterImgAlt: 'Casino Model',
    logoAlt: '568Win',
    logoWidth: '200px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-2px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'yellow',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'wm-casino',
    provider_id: 3002,
    name: 'WM Casino',
    characterImgAlt: 'Casino Model',
    logoAlt: 'WM Casino',
    logoWidth: '200px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[5px] bottom-[-55px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'ion-casino',
    provider_id: 3003,
    name: 'ION Casino',
    characterImgAlt: 'Casino Model',
    logoAlt: 'ION Casino',
    logoWidth: '200px',
    logoTop: '-5px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[5px] bottom-[-45px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'cyan',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'sa-gaming',
    provider_id: 3004,
    name: 'SA Gaming',
    characterImgAlt: 'Casino Model',
    logoAlt: 'SA Gaming',
    logoWidth: '200px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-5px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'evolution-gaming',
    provider_id: 3005,
    name: 'Evolution Gaming',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Evolution Gaming',
    logoWidth: '200px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'purple',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'allbet',
    provider_id: 3006,
    name: 'Allbet',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Allbet',
    logoWidth: '200px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-120px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'green-dragon',
    provider_id: 3007,
    name: 'Green Dragon',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Green Dragon',
    logoWidth: '200px',
    logoTop: '-15px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-55px]',
    characterCentered: true,
    glowColor: 'green',
    glowColorHover: 'cyan',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'pragmatic-casino',
    provider_id: 3008,
    name: 'Pragmatic Play',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Pragmatic Play',
    logoWidth: '200px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-20px] bottom-[-90px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'yellow',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'yb-live',
    provider_id: 3009,
    name: 'YB Live',
    characterImgAlt: 'Casino Model',
    logoAlt: 'YB Live',
    logoWidth: '200px',
    logoTop: '-5px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[0px] bottom-[-80px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'afb777-casino',
    provider_id: 3010,
    name: 'AFB777 Gaming',
    characterImgAlt: 'Casino Model',
    logoAlt: 'AFB777 Gaming',
    logoWidth: '200px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[75%]',
    characterPosition: 'left-[-35px] bottom-[-120px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'playtech',
    provider_id: 3011,
    name: 'Playtech',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Playtech',
    logoWidth: '200px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-60px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'asia-gaming',
    provider_id: 3012,
    name: 'Asia Gaming',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Asia Gaming',
    logoWidth: '200px',
    logoTop: '30px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-60px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'cyan',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'wcasino',
    provider_id: 3013,
    name: 'WCasino Online',
    characterImgAlt: 'Casino Model',
    logoAlt: 'WCasino Online',
    logoWidth: '200px',
    logoTop: '-5px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-15px] bottom-[-60px]',
    characterCentered: true,
    glowColor: 'green',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'gameplay-interactive',
    provider_id: 3014,
    name: 'Gameplay Interactive',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Gameplay Interactive',
    logoWidth: '200px',
    logoTop: '15px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-15px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'yellow',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'ezugi',
    provider_id: 3015,
    name: 'Ezugi',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Ezugi',
    logoWidth: '200px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'cyan',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'a-star',
    provider_id: 3016,
    name: 'A Star',
    characterImgAlt: 'Casino Model',
    logoAlt: 'A Star',
    logoWidth: '200px',
    logoTop: '22px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-68px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'grand-live',
    provider_id: 3017,
    name: 'Grand Live',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Grand Live',
    logoWidth: '200px',
    logoTop: '22px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'purple',
    glowColorHover: 'cyan',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'lucky-heart-live',
    provider_id: 3019,
    name: 'Lucky Heart Live',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Lucky Heart Live',
    logoWidth: '200px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'red',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'casinogame',
    provider_id: 3020,
    name: 'Casinogame',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Casinogame',
    logoWidth: '200px',
    logoTop: '22px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'dream-gaming',
    provider_id: 3021,
    name: 'DreamGaming',
    characterImgAlt: 'Casino Model',
    logoAlt: 'DreamGaming',
    logoWidth: '200px',
    logoTop: '18px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'mac88',
    provider_id: 3022,
    name: 'MAC88',
    characterImgAlt: 'Casino Model',
    logoAlt: 'MAC88',
    logoWidth: '200px',
    logoTop: '22px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'sexy-gaming',
    provider_id: 3023,
    name: 'Sexy Gaming',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Sexy Gaming',
    logoWidth: '200px',
    logoTop: '18px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'purple',
    animationPrefix: 'casinomodel',
  },
  {
    id: 'microgaming-live',
    provider_id: 3018,
    name: 'Microgaming',
    characterImgAlt: 'Casino Model',
    logoAlt: 'Microgaming',
    logoWidth: '200px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-5px] bottom-[-65px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'casinomodel',
  },
]

export const casinoProviders = mapProviderImages(casinoProvidersRaw)

// ========== TOGEL PROVIDERS ==========
// Paired: togel1 + loteg1, togel2 + loteg2
const togelProvidersRaw = [
  {
    id: 'hongkong-lotto',
    provider_id: 5001,
    name: 'Hong Kong Lotto',
    characterImgAlt: 'Togel Model',
    logoAlt: 'Hong Kong Lotto',
    logoWidth: '110px',
    logoTop: '10px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-30px] bottom-[-100px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'yellow',
    animationPrefix: 'togelmodel',
  },
  {
    id: 'sydney-lotto',
    provider_id: 5002,
    name: 'Sydney Lotto',
    characterImgAlt: 'Togel Model',
    logoAlt: 'Sydney Lotto',
    logoWidth: '110px',
    logoTop: '10px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-5px] bottom-[-80px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'togelmodel',
  },
  {
    id: 'singapore-togel',
    provider_id: 5003,
    name: 'Singapore',
    characterImgAlt: 'Singapore Model',
    logoAlt: 'Singapore',
    logoWidth: '100px',
    logoTop: '3px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[5px] bottom-[-100px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'togelmodel',
  },
  {
    id: 'kamboja-togel',
    provider_id: 5004,
    name: 'Kamboja',
    characterImgAlt: 'Kamboja Model',
    logoAlt: 'Kamboja',
    logoWidth: '160px',
    logoTop: '35px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px] bottom-[-80px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'yellow',
    animationPrefix: 'togelmodel',
  },
  {
    id: 'taiwan-togel',
    provider_id: 5005,
    name: 'Taiwan',
    characterImgAlt: 'Taiwan Model',
    logoAlt: 'Taiwan',
    logoWidth: '150px',
    logoTop: '45px',
    logoLeft: '46%',
    characterWidth: 'w-[95%]',
    characterPosition: 'left-[-50px] bottom-[-60px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'white',
    animationPrefix: 'togelmodel',
  },
  {
    id: 'hongkong-togel',
    provider_id: 5006,
    name: 'Hongkong',
    characterImgAlt: 'Hongkong Model',
    logoAlt: 'Hongkong',
    logoWidth: '110px',
    logoTop: '6px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[5px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'purple',
    glowColorHover: 'cyan',
    animationPrefix: 'togelmodel',
  },
  {
    id: 'sidney-togel',
    provider_id: 5007,
    name: 'Sidney',
    characterImgAlt: 'Sidney Model',
    logoAlt: 'Sydney Pools',
    logoWidth: '110px',
    logoTop: '8px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-10px] bottom-[-80px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'yellow',
    animationPrefix: 'togelmodel',
  },
]

export const togelProviders = mapProviderImages(togelProvidersRaw)

// Rename existing providers to slotProviders for clarity
export const slotProviders = providers

// Total slots to show (including empty "Coming Soon" slots)
export const TOTAL_SLOTS = 56
export const TOTAL_SPORTS_SLOTS = 12
export const TOTAL_CASINO_SLOTS = 24
export const TOTAL_TOGEL_SLOTS = 8

// ========== FISHING PROVIDERS ==========
const fishingProvidersRaw = [
  {
    id: 'microgaming-fishing',
    provider_id: 2001,
    name: 'Microgaming',
    characterImgAlt: 'Shark Warrior',
    logoAlt: 'Microgaming',
    logoWidth: '180px',
    logoTop: '16px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-30px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'green',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'jdb-fishing-1',
    provider_id: 2002,
    name: 'JDB',
    characterImgAlt: 'Pirate Shark',
    logoAlt: 'JDB',
    logoWidth: '180px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[45%]',
    characterPosition: 'left-[5px] bottom-[-60px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'yellow',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'jili-fishing',
    provider_id: 2003,
    name: 'JILI',
    characterImgAlt: 'Treasure Shark',
    logoAlt: 'JILI',
    logoWidth: '150px',
    logoTop: '5px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-15px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'funky-fishing',
    provider_id: 2004,
    name: 'Funky Games',
    characterImgAlt: 'Pirate Rider',
    logoAlt: 'Funky Games',
    logoWidth: '180px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[5px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'white',
    glowColorHover: 'cyan',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'dragoon-fishing',
    provider_id: 2005,
    name: 'Dragoon Soft',
    characterImgAlt: 'Captain Shark',
    logoAlt: 'Dragoon Soft',
    logoWidth: '200px',
    logoTop: '45px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-20px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'cq9-fishing',
    provider_id: 2006,
    name: 'JDB',
    characterImgAlt: 'Pirate Shark',
    logoAlt: 'JDB',
    logoWidth: '180px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[50%]',
    characterPosition: 'left-[-5px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'red',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'fachai-fishing',
    provider_id: 2007,
    name: 'FA Chai',
    characterImgAlt: 'Pirate Shark Captain',
    logoAlt: 'FA Chai Fishing',
    logoWidth: '130px',
    logoTop: '5px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-15px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'cyan',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'brand-bt-gaming',
    provider_id: 2008,
    name: 'BT Gaming',
    characterImgAlt: 'Fishing character',
    logoAlt: 'BT Gaming',
    logoWidth: '180px',
    logoTop: '16px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-30px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'green',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'brand-v-plus',
    provider_id: 2009,
    name: 'V Plus',
    characterImgAlt: 'Fishing character',
    logoAlt: 'V Plus',
    logoWidth: '180px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[45%]',
    characterPosition: 'left-[5px] bottom-[-60px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'yellow',
    animationPrefix: 'fishingchar',
  },
  {
    id: 'brand-ka-gaming',
    provider_id: 2010,
    name: 'KA Gaming',
    characterImgAlt: 'Fishing character',
    logoAlt: 'KA Gaming',
    logoWidth: '150px',
    logoTop: '5px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-15px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'fishingchar',
  },
]

export const fishingProviders = mapProviderImages(fishingProvidersRaw)

export const TOTAL_FISHING_SLOTS = 12

// ========== ARCADE PROVIDERS ==========
const arcadeProvidersRaw = [
  {
    id: 'aviatrix-arcade',
    provider_id: 6001,
    name: 'Aviatrix',
    characterImgAlt: 'Aviatrix Plane',
    logoAlt: 'Aviatrix',
    logoWidth: '180px',
    logoTop: '-15px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-30px] bottom-[20px]',
    characterCentered: true,
    glowColor: 'purple',
    glowColorHover: 'white',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'kingmidas-arcade',
    provider_id: 6002,
    name: 'King Midas',
    characterImgAlt: 'King Midas',
    logoAlt: 'King Midas',
    logoWidth: '200px',
    logoTop: '45px',
    logoLeft: '46%',
    characterWidth: 'w-[85%]',
    characterPosition: 'left-[-55px] bottom-[-85px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'sbobet-arcade',
    provider_id: 6003,
    name: 'SBOBET',
    characterImgAlt: 'Hamster Coin',
    logoAlt: 'SBOBET',
    logoWidth: '180px',
    logoTop: '45px',
    logoLeft: '46%',
    characterWidth: 'w-[65%]',
    characterPosition: 'left-[-20px] bottom-[-60px]',
    characterCentered: true,
    glowColor: 'purple',
    glowColorHover: 'cyan',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'spribe-arcade',
    provider_id: 6004,
    name: 'Spribe',
    characterImgAlt: 'Pilot Hamster',
    logoAlt: 'Spribe',
    logoWidth: '180px',
    logoTop: '-10px',
    logoLeft: '46%',
    characterWidth: 'w-[105%]',
    characterPosition: 'left-[-90px] bottom-[-160px]',
    characterCentered: true,
    glowColor: 'white',
    glowColorHover: 'yellow',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'brand-arc-jdb',
    provider_id: 6005,
    name: 'JDB',
    characterImgAlt: 'Arcade character',
    logoAlt: 'JDB',
    logoWidth: '180px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-25px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'orange',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'brand-arc-cq9',
    provider_id: 6006,
    name: 'CQ9 Gaming',
    characterImgAlt: 'Arcade character',
    logoAlt: 'CQ9 Gaming',
    logoWidth: '180px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[55%]',
    characterPosition: 'left-[-15px] bottom-[-55px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'yellow',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'brand-arc-fachai',
    provider_id: 6007,
    name: 'FA Chai',
    characterImgAlt: 'Arcade character',
    logoAlt: 'FA Chai',
    logoWidth: '170px',
    logoTop: '18px',
    logoLeft: '46%',
    characterWidth: 'w-[58%]',
    characterPosition: 'left-[-20px] bottom-[-52px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'blue',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'brand-arc-rich88',
    provider_id: 6008,
    name: 'Rich88',
    characterImgAlt: 'Arcade character',
    logoAlt: 'Rich88',
    logoWidth: '180px',
    logoTop: '16px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-25px] bottom-[-50px]',
    characterCentered: true,
    glowColor: 'purple',
    glowColorHover: 'pink',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'brand-arc-askmeslot',
    provider_id: 6009,
    name: 'AskMeSlot',
    characterImgAlt: 'Arcade character',
    logoAlt: 'AskMeSlot',
    logoWidth: '175px',
    logoTop: '18px',
    logoLeft: '46%',
    characterWidth: 'w-[62%]',
    characterPosition: 'left-[-28px] bottom-[-48px]',
    characterCentered: true,
    glowColor: 'yellow',
    glowColorHover: 'white',
    animationPrefix: 'arcadechar',
  },
  {
    id: 'brand-arc-six',
    provider_id: 6010,
    name: 'Arcade',
    characterImgAlt: 'Arcade character',
    logoAlt: 'Arcade',
    logoWidth: '180px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[58%]',
    characterPosition: 'left-[-22px] bottom-[-52px]',
    characterCentered: true,
    glowColor: 'green',
    glowColorHover: 'cyan',
    animationPrefix: 'arcadechar',
  },
]

export const arcadeProviders = mapProviderImages(arcadeProvidersRaw)

export const TOTAL_ARCADE_SLOTS = 8

// ========== ESPORTS PROVIDERS (91xx) ==========
const esportsProvidersRaw = [
  {
    id: 'ia-esports',
    provider_id: 9101,
    name: 'IA Esports',
    characterImgAlt: 'Esports character',
    logoAlt: 'IA Esports',
    logoWidth: '190px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-24px] bottom-[-52px]',
    characterCentered: true,
    glowColor: 'cyan',
    glowColorHover: 'white',
    animationPrefix: 'esportschar',
  },
  {
    id: 'sbobetesports',
    provider_id: 9102,
    name: 'SBOBET Esports',
    characterImgAlt: 'Esports character',
    logoAlt: 'SBOBET Esports',
    logoWidth: '190px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-24px] bottom-[-52px]',
    characterCentered: true,
    glowColor: 'blue',
    glowColorHover: 'cyan',
    animationPrefix: 'esportschar',
  },
  {
    id: 'hp-gaming',
    provider_id: 9103,
    name: '100HP Gaming',
    characterImgAlt: 'Esports character',
    logoAlt: '100HP Gaming',
    logoWidth: '190px',
    logoTop: '20px',
    logoLeft: '46%',
    characterWidth: 'w-[60%]',
    characterPosition: 'left-[-24px] bottom-[-52px]',
    characterCentered: true,
    glowColor: 'orange',
    glowColorHover: 'red',
    animationPrefix: 'esportschar',
  },
]

export const esportsProviders = mapProviderImages(esportsProvidersRaw)

export const TOTAL_ESPORTS_SLOTS = 8

// ========== CRUSH PROVIDERS (9xxx) ==========
const crushGlowPairs = [
  ['cyan', 'purple'],
  ['purple', 'cyan'],
  ['orange', 'yellow'],
  ['yellow', 'orange'],
  ['red', 'orange'],
  ['cyan', 'white'],
  ['white', 'cyan'],
  ['purple', 'yellow'],
  ['green', 'cyan'],
]

const crushProvidersRaw = crushGlowPairs.map(([glowColor, glowColorHover], i) => ({
  id: `rocket-${i + 1}`,
  provider_id: 9001 + i,
  name: `Crush ${i + 1}`,
  characterImgAlt: 'Crush character',
  logoAlt: 'Crush',
  logoWidth: '180px',
  logoTop: '20px',
  logoLeft: '46%',
  characterWidth: 'w-[58%]',
  characterPosition: 'left-[-22px] bottom-[-52px]',
  characterCentered: true,
  glowColor,
  glowColorHover,
  animationPrefix: 'crushchar',
}))

export const crushProviders = mapProviderImages(crushProvidersRaw)

export const TOTAL_CRUSH_SLOTS = 8

// ========== POKER PROVIDERS ==========
const pokerProvidersRaw = [
  {
    id: 'millionaire-poker',
    provider_id: 7001,
    name: 'Millionaire Poker',
    characterImgAlt: 'Poker Cards',
    logoAlt: 'Millionaire Poker',
    logoWidth: '200px',
    logoTop: '25px',
    logoLeft: '46%',
    characterWidth: 'w-[85%]',
    characterPosition: 'left-[-50px] bottom-[-70px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'yellow',
    animationPrefix: 'pokerchar',
  },
]

export const pokerProviders = mapProviderImages(pokerProvidersRaw)

export const TOTAL_POKER_SLOTS = 8

// ========== COCK FIGHTING PROVIDERS ==========
const cockfightProvidersRaw = [
  {
    id: 'ga28-cockfight',
    provider_id: 8001,
    name: 'GA28',
    characterImgAlt: 'Fighting Roosters',
    logoAlt: 'GA28',
    logoWidth: '180px',
    logoTop: '40px',
    logoLeft: '46%',
    characterWidth: 'w-[95%]',
    characterPosition: 'left-[-75px] bottom-[-100px]',
    characterCentered: true,
    glowColor: 'red',
    glowColorHover: 'orange',
    animationPrefix: 'cockchar',
  },
]

export const cockfightProviders = mapProviderImages(cockfightProvidersRaw)

export const TOTAL_COCKFIGHT_SLOTS = 8